//const variables from product reducer
//the values are the same, but give it const to use in other files

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_ONE_REQUEST = "PRODUCT_ONE_REQUEST";
export const PRODUCT_ONE_SUCCESS = "PRODUCT_ONE_SUCCESS";
export const PRODUCT_ONE_FAIL = "PRODUCT_ONE_FAIL";

export const PRODUCT_CREATE_REV_REQUEST = "PRODUCT_CREATE_REV_REQUEST";
export const PRODUCT_CREATE_REV_SUCCESS = "PRODUCT_CREATE_REV_SUCCESS";
export const PRODUCT_CREATE_REV_FAIL = "PRODUCT_CREATE_REV_FAIL";
export const PRODUCT_CREATE_REV_RESET = "PRODUCT_CREATE_REV_RESET";
